spring:
  jpa:
    hibernate:
      ddl-auto: update
  resources:
    cache-period: 691200
    chain:
      strategy:
        content:
          enabled: true
security:
  ignored:
    - /css/**
    - /js/**
    - /images/**
    - /favicon.ico
