spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  resources:
    cache-period: 691200
    chain:
      strategy:
        content:
          enabled: true
  datasource:
    name: db
  freemarker:
    settings:
      template_exception_handler: rethrow
  jackson:
    mapper:
      accept-case-insensitive-enums: true
      accept-case-insensitive-properties: true
    serialization:
      indent-output: true
server:
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'
    internal-proxies: '.*'
  compression:
    enabled: true
    mime-types:
    - application/json
    - application/xml
    - text/html
    - text/xml
    - text/plain
    - text/css
