spring:
  jpa:
    hibernate:
      ddl-auto: update
  resources:
    cache-period: 691200
    chain:
      strategy:
        content:
          enabled: true
security:
  ignored:
  - /css/**
  - /js/**
  - /images/**
  - /favicon.ico
server:
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'
  compression:
    enabled: true
    mime-types:
    - application/json
    - application/xml
    - text/html
    - text/xml
    - text/plain
    - text/css
